export const ApiConstants ={
      apiURL : 'http://prod.piharwa.com/',
      // apiURL : 'http://localhost:3001/',
      categorylist: 'api/v1/category/list',
      featuredProducts: 'api/v1/product/featured-product/list',
      allcategoryList: 'api/v1/categories/list/all',
      latestArrivals: 'api/v1/product/latest-arrival/list',
      testimonialList: 'api/v1/testimonials/list',
      productlist:'api/v1/product/list',
      singleproduct:'api/v1/product/single-product/',
      registerApi:'api/v1/buyers/register',
      loginApi:'api/v1/buyers/login',
      otpToken:'api/v1/buyers/verify/otp',
      mainCategoryList:'api/v1/main/category/list',
      blogListApi: 'api/v1/blog/list',
      blogDetailsApi: 'api/v1/blog/single-blog/',
      listAddress: 'api/v1/buyer/list/address/details',
      defaultAddress: 'api/v1/buyer/default/address/details',
      addaddress:'api/v1/buyer/add/address/details',
      updateAddress:'api/v1/buyer/edit/address/details',
      deleteAddress:'api/v1/buyer/delete/address/details',
      profileApi:'api/v1/buyers/details',
      createOrderId:'api/v1/checkout/order/create',
      verifyPaymentApi:'api/v1/checkout/payment/verify',
      orderListApi: 'api/v1/buyer/order/list',
      addToCart: 'api/v1/cart/add/details',
      getCartList: 'api/v1/cart/list',
      updateCart: 'api/v1/cart/update/details',
      deleteFromCart: 'api/v1/cart/delete/details/',
      // /api/v1/buyer/delete/address/details/{addressId}
}
